name: saathi
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Icons
  cupertino_icons: ^1.0.8
  
  # State Management
  provider: ^6.1.1
  
  # Database & Storage
  sqflite_sqlcipher: ^3.1.0+1
  path_provider: ^2.1.2
  path: ^1.9.0
  
  # Security & Encryption
  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.3
  pointycastle: ^3.9.1
  
  # Nearby Connections (Phase 2 - Replaced BLE)
  nearby_connections: ^4.3.0
  permission_handler: ^11.3.1
  location: ^5.0.0
  
  # Utilities
  uuid: ^4.5.2
  intl: ^0.19.0
  share_plus: ^7.2.2
  file_picker: ^8.1.4
  package_info_plus: ^9.0.0
  archive: ^3.4.0
  
  # UI & Fonts
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  
  assets:
    - assets/content/chapters/en/chapters/
    - assets/content/chapters/mr/chapters/
    - assets/images/
    - assets/images/chapters/1/
    - assets/images/chapters/5/
    - assets/images/chapters/7/
  
  # Fonts will be loaded via google_fonts package
  # No need to bundle font files
